/**
 * Patient Billing – Connected to shared hospital billing store.
 * Bills are generated by the system when appointments are completed.
 * Patient can pay pending bills online here.
 */

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import toast from "react-hot-toast";
import { billingApi } from "../services/api";
import { useAuth } from "../context/AuthContext";
import Spinner from "../components/Spinner";
import { formatINR, formatDateIndian } from "../utils/formatIndian";
import {
  Search,
  Download,
  FileText,
  CheckCircle2,
  Clock,
  Landmark,
  CreditCard,
  Smartphone,
  AlertCircle,
  X,
} from "lucide-react";

const PAYMENT_METHODS = [
  "UPI",
  "Credit Card",
  "Debit Card",
  "Net Banking",
  "Cash",
];

function StatusBadge({ status }) {
  const cfg = {
    paid: { bg: "rgba(16,185,129,0.12)", color: "#10B981", label: "Paid" },
    pending: {
      bg: "rgba(245,158,11,0.12)",
      color: "#F59E0B",
      label: "Pending",
    },
    overdue: { bg: "rgba(239,68,68,0.12)", color: "#EF4444", label: "Overdue" },
  };
  const s = cfg[status] || cfg.pending;
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 5,
        padding: "4px 12px",
        borderRadius: 999,
        background: s.bg,
        color: s.color,
        fontSize: 11,
        fontWeight: 800,
        textTransform: "uppercase",
        letterSpacing: "0.07em",
      }}
    >
      <span
        style={{
          width: 6,
          height: 6,
          borderRadius: "50%",
          background: s.color,
        }}
      />
      {s.label}
    </span>
  );
}

export default function PatientBilling() {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [payingId, setPayingId] = useState(null);
  const [payMethod, setPayMethod] = useState("UPI");
  const [paying, setPaying] = useState(false);
  const [expanded, setExpanded] = useState(null);

  useEffect(() => {
    load();
  }, []);

  const load = async () => {
    try {
      const patientId = user?.id;
      const res = await billingApi.getForPatient(patientId);
      setInvoices(res.data);
    } catch {
      toast.error("Failed to load billing history");
    } finally {
      setLoading(false);
    }
  };

  const handlePay = async () => {
    if (!payingId) return;
    setPaying(true);
    try {
      await billingApi.pay(payingId, payMethod);
      toast.success("✅ Payment successful! Your receipt has been generated.");
      setPayingId(null);
      load();
    } catch {
      toast.error("Payment failed. Please try again.");
    } finally {
      setPaying(false);
    }
  };

  if (loading) {
    return (
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          minHeight: 300,
        }}
      >
        <Spinner size="lg" />
      </div>
    );
  }

  const filtered = invoices.filter(
    (inv) =>
      !search ||
      inv.id?.toLowerCase().includes(search.toLowerCase()) ||
      inv.doctorName?.toLowerCase().includes(search.toLowerCase()) ||
      inv.department?.toLowerCase().includes(search.toLowerCase()),
  );

  const totalPaid = invoices
    .filter((i) => i.status === "paid")
    .reduce((sum, i) => sum + (i.totalAmount || 0), 0);
  const totalPending = invoices
    .filter((i) => i.status === "pending")
    .reduce((sum, i) => sum + (i.totalAmount || 0), 0);

  const payingInvoice = invoices.find((i) => i.id === payingId);

  return (
    <div
      style={{
        fontFamily: "'Inter', system-ui, sans-serif",
        maxWidth: 900,
        margin: "0 auto",
        paddingBottom: 40,
      }}
    >
      {/* Header */}
      <div style={{ marginBottom: 28 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: 6,
          }}
        >
          <div
            style={{
              width: 40,
              height: 40,
              borderRadius: 12,
              background: "linear-gradient(135deg, #F59E0B, #EF4444)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              boxShadow: "0 4px 12px rgba(245,158,11,0.30)",
            }}
          >
            <Landmark style={{ width: 20, height: 20, color: "#fff" }} />
          </div>
          <h2
            style={{
              fontSize: 26,
              fontWeight: 900,
              color: "#0F172A",
              letterSpacing: "-0.02em",
            }}
          >
            Billing & Payments
          </h2>
        </div>
        <p
          style={{
            color: "#64748B",
            fontSize: 14,
            fontWeight: 500,
            marginLeft: 52,
          }}
        >
          Bills are generated automatically when your visit is completed.
        </p>
      </div>

      {/* Summary cards */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
          gap: 14,
          marginBottom: 28,
        }}
      >
        {[
          {
            label: "Total Invoices",
            value: invoices.length,
            color: "#2563EB",
            bg: "rgba(37,99,235,0.08)",
            icon: FileText,
          },
          {
            label: "Total Paid",
            value: formatINR(totalPaid),
            color: "#10B981",
            bg: "rgba(16,185,129,0.08)",
            icon: CheckCircle2,
          },
          {
            label: "Pending Amount",
            value: formatINR(totalPending),
            color: "#F59E0B",
            bg: "rgba(245,158,11,0.08)",
            icon: Clock,
          },
        ].map(({ label, value, color, bg, icon: Icon }) => (
          <div
            key={label}
            style={{
              background: "#fff",
              borderRadius: 14,
              padding: "18px 20px",
              border: "1px solid #E2E8F0",
              boxShadow: "0 2px 10px rgba(0,0,0,0.04)",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                marginBottom: 8,
              }}
            >
              <div
                style={{
                  width: 34,
                  height: 34,
                  borderRadius: 9,
                  background: bg,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <Icon style={{ width: 16, height: 16, color }} />
              </div>
              <p
                style={{
                  fontSize: 11,
                  fontWeight: 700,
                  color: "#94A3B8",
                  textTransform: "uppercase",
                  letterSpacing: "0.07em",
                }}
              >
                {label}
              </p>
            </div>
            <p style={{ fontSize: 20, fontWeight: 900, color: "#0F172A" }}>
              {value}
            </p>
          </div>
        ))}
      </div>

      {/* Search */}
      <div style={{ position: "relative", marginBottom: 20, maxWidth: 340 }}>
        <Search
          style={{
            position: "absolute",
            left: 12,
            top: "50%",
            transform: "translateY(-50%)",
            width: 16,
            height: 16,
            color: "#94A3B8",
          }}
        />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search invoice, doctor, dept..."
          style={{
            width: "100%",
            paddingLeft: 36,
            paddingRight: 14,
            paddingTop: 10,
            paddingBottom: 10,
            border: "1.5px solid #E2E8F0",
            borderRadius: 10,
            fontSize: 13,
            fontWeight: 600,
            outline: "none",
            color: "#0F172A",
            boxSizing: "border-box",
          }}
        />
      </div>

      {/* Invoice list */}
      {filtered.length === 0 ? (
        <div
          style={{
            textAlign: "center",
            padding: "48px 24px",
            background: "#fff",
            borderRadius: 16,
            border: "1.5px dashed #E2E8F0",
          }}
        >
          <FileText
            style={{
              width: 40,
              height: 40,
              color: "#CBD5E1",
              margin: "0 auto 12px",
            }}
          />
          <h3
            style={{
              fontSize: 16,
              fontWeight: 700,
              color: "#1E293B",
              marginBottom: 6,
            }}
          >
            No Bills Yet
          </h3>
          <p style={{ color: "#94A3B8", fontSize: 13, fontWeight: 500 }}>
            Bills will appear here automatically after your doctor completes
            your appointment.
          </p>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {filtered.map((inv, i) => (
            <motion.div
              key={inv.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.05 }}
              style={{
                background: "#fff",
                borderRadius: 14,
                border: "1px solid #E2E8F0",
                borderLeft: `4px solid ${inv.status === "paid" ? "#10B981" : "#F59E0B"}`,
                boxShadow: "0 2px 10px rgba(0,0,0,0.04)",
                overflow: "hidden",
                transition: "box-shadow 0.2s ease",
              }}
            >
              <div
                style={{
                  padding: "16px 20px",
                  cursor: "pointer",
                  display: "flex",
                  alignItems: "center",
                  gap: 16,
                  flexWrap: "wrap",
                }}
                onClick={() => setExpanded(expanded === inv.id ? null : inv.id)}
              >
                {/* Invoice icon */}
                <div
                  style={{
                    width: 42,
                    height: 42,
                    borderRadius: 10,
                    flexShrink: 0,
                    background:
                      inv.status === "paid"
                        ? "rgba(16,185,129,0.10)"
                        : "rgba(245,158,11,0.10)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <FileText
                    style={{
                      width: 20,
                      height: 20,
                      color: inv.status === "paid" ? "#10B981" : "#F59E0B",
                    }}
                  />
                </div>

                {/* Invoice info */}
                <div style={{ flex: 1, minWidth: 140 }}>
                  <p
                    style={{
                      fontSize: 13,
                      fontWeight: 900,
                      color: "#0F172A",
                      marginBottom: 2,
                    }}
                  >
                    {inv.id}
                  </p>
                  <p
                    style={{ fontSize: 12, color: "#64748B", fontWeight: 600 }}
                  >
                    {inv.doctorName} · {inv.department}
                  </p>
                  <p
                    style={{
                      fontSize: 11,
                      color: "#94A3B8",
                      fontWeight: 500,
                      marginTop: 2,
                    }}
                  >
                    {formatDateIndian(inv.date)}
                  </p>
                </div>

                {/* Amount */}
                <p style={{ fontSize: 20, fontWeight: 900, color: "#0F172A" }}>
                  {formatINR(inv.totalAmount)}
                </p>

                {/* Status */}
                <StatusBadge status={inv.status} />

                {/* Pay button */}
                {inv.status === "pending" && (
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setPayingId(inv.id);
                      setPayMethod("UPI");
                    }}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 6,
                      padding: "8px 16px",
                      borderRadius: 9,
                      background: "linear-gradient(135deg, #2563EB, #06B6D4)",
                      border: "none",
                      color: "#fff",
                      fontSize: 12,
                      fontWeight: 800,
                      cursor: "pointer",
                      boxShadow: "0 4px 12px rgba(37,99,235,0.25)",
                      flexShrink: 0,
                    }}
                  >
                    <CreditCard style={{ width: 14, height: 14 }} /> Pay Now
                  </button>
                )}
              </div>

              {/* Expanded invoice details */}
              <AnimatePresence>
                {expanded === inv.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    style={{ overflow: "hidden" }}
                  >
                    <div
                      style={{
                        borderTop: "1px solid #F1F5F9",
                        padding: "16px 20px",
                        background: "#FAFBFF",
                      }}
                    >
                      <p
                        style={{
                          fontSize: 11,
                          fontWeight: 700,
                          color: "#94A3B8",
                          textTransform: "uppercase",
                          letterSpacing: "0.08em",
                          marginBottom: 10,
                        }}
                      >
                        Invoice Details
                      </p>
                      <div
                        style={{
                          display: "flex",
                          flexDirection: "column",
                          gap: 6,
                        }}
                      >
                        {(inv.items || []).map((item, j) => (
                          <div
                            key={j}
                            style={{
                              display: "flex",
                              justifyContent: "space-between",
                              fontSize: 13,
                              padding: "6px 0",
                              borderBottom: "1px solid #F1F5F9",
                            }}
                          >
                            <span style={{ color: "#475569", fontWeight: 600 }}>
                              {item.description}
                            </span>
                            <span style={{ color: "#0F172A", fontWeight: 800 }}>
                              {formatINR(item.amount)}
                            </span>
                          </div>
                        ))}
                        <div
                          style={{
                            display: "flex",
                            justifyContent: "space-between",
                            fontSize: 15,
                            fontWeight: 900,
                            color: "#0F172A",
                            paddingTop: 8,
                            marginTop: 4,
                            borderTop: "2px solid #E2E8F0",
                          }}
                        >
                          <span>Total</span>
                          <span>{formatINR(inv.totalAmount)}</span>
                        </div>
                      </div>
                      {inv.status === "paid" && (
                        <div
                          style={{
                            marginTop: 12,
                            padding: "10px 14px",
                            background: "rgba(16,185,129,0.08)",
                            borderRadius: 9,
                            border: "1px solid rgba(16,185,129,0.20)",
                            fontSize: 12,
                            color: "#10B981",
                            fontWeight: 700,
                          }}
                        >
                          ✅ Paid via {inv.paymentMethod} on{" "}
                          {formatDateIndian(inv.paymentDate)}
                        </div>
                      )}
                      <button
                        style={{
                          marginTop: 12,
                          display: "flex",
                          alignItems: "center",
                          gap: 6,
                          padding: "8px 16px",
                          border: "1.5px solid #E2E8F0",
                          borderRadius: 9,
                          fontSize: 12,
                          fontWeight: 700,
                          color: "#475569",
                          background: "#fff",
                          cursor: "pointer",
                        }}
                        onClick={() =>
                          toast.success("Receipt download feature coming soon!")
                        }
                      >
                        <Download style={{ width: 14, height: 14 }} /> Download
                        Receipt
                      </button>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      )}

      {/* Payment Modal */}
      <AnimatePresence>
        {payingId && payingInvoice && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={{
              position: "fixed",
              inset: 0,
              background: "rgba(0,0,0,0.50)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              zIndex: 50,
              padding: 16,
            }}
            onClick={() => setPayingId(null)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.93, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.93 }}
              onClick={(e) => e.stopPropagation()}
              style={{
                background: "#fff",
                borderRadius: 20,
                padding: 28,
                width: "100%",
                maxWidth: 420,
                boxShadow: "0 24px 60px rgba(0,0,0,0.20)",
              }}
            >
              {/* Modal header */}
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                  marginBottom: 20,
                }}
              >
                <div>
                  <h3
                    style={{ fontSize: 18, fontWeight: 900, color: "#0F172A" }}
                  >
                    Pay Invoice
                  </h3>
                  <p
                    style={{ fontSize: 12, color: "#94A3B8", fontWeight: 600 }}
                  >
                    {payingInvoice.id} · {payingInvoice.department}
                  </p>
                </div>
                <button
                  onClick={() => setPayingId(null)}
                  style={{
                    background: "none",
                    border: "none",
                    cursor: "pointer",
                    color: "#94A3B8",
                    padding: 4,
                  }}
                >
                  <X style={{ width: 20, height: 20 }} />
                </button>
              </div>

              {/* Amount */}
              <div
                style={{
                  background: "linear-gradient(135deg, #2563EB, #06B6D4)",
                  borderRadius: 14,
                  padding: "20px 22px",
                  marginBottom: 20,
                  textAlign: "center",
                }}
              >
                <p
                  style={{
                    fontSize: 13,
                    color: "rgba(255,255,255,0.75)",
                    fontWeight: 600,
                    marginBottom: 4,
                  }}
                >
                  Amount Due
                </p>
                <p style={{ fontSize: 32, fontWeight: 900, color: "#fff" }}>
                  {formatINR(payingInvoice.totalAmount)}
                </p>
                <p
                  style={{
                    fontSize: 12,
                    color: "rgba(255,255,255,0.70)",
                    fontWeight: 600,
                    marginTop: 4,
                  }}
                >
                  {payingInvoice.doctorName} ·{" "}
                  {formatDateIndian(payingInvoice.date)}
                </p>
              </div>

              {/* Payment method */}
              <p
                style={{
                  fontSize: 11,
                  fontWeight: 700,
                  color: "#64748B",
                  textTransform: "uppercase",
                  letterSpacing: "0.08em",
                  marginBottom: 10,
                }}
              >
                Select Payment Method
              </p>
              <div
                style={{
                  display: "grid",
                  gridTemplateColumns: "repeat(3, 1fr)",
                  gap: 8,
                  marginBottom: 20,
                }}
              >
                {PAYMENT_METHODS.map((m) => (
                  <button
                    key={m}
                    onClick={() => setPayMethod(m)}
                    style={{
                      padding: "10px 8px",
                      borderRadius: 9,
                      fontSize: 12,
                      fontWeight: 700,
                      cursor: "pointer",
                      transition: "all 0.15s",
                      background:
                        payMethod === m ? "rgba(37,99,235,0.10)" : "#F8FAFC",
                      border: `1.5px solid ${payMethod === m ? "#2563EB" : "#E2E8F0"}`,
                      color: payMethod === m ? "#2563EB" : "#64748B",
                    }}
                  >
                    {m === "UPI" ? "📱 " : m.includes("Card") ? "💳 " : "🏦 "}
                    {m}
                  </button>
                ))}
              </div>

              <button
                onClick={handlePay}
                disabled={paying}
                style={{
                  width: "100%",
                  padding: "14px",
                  background: "linear-gradient(135deg, #10B981, #059669)",
                  border: "none",
                  borderRadius: 12,
                  color: "#fff",
                  fontSize: 15,
                  fontWeight: 900,
                  cursor: paying ? "not-allowed" : "pointer",
                  opacity: paying ? 0.7 : 1,
                  boxShadow: "0 4px 16px rgba(16,185,129,0.30)",
                }}
              >
                {paying
                  ? "Processing…"
                  : `✅ Pay ${formatINR(payingInvoice.totalAmount)} via ${payMethod}`}
              </button>

              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 6,
                  marginTop: 12,
                  justifyContent: "center",
                }}
              >
                <AlertCircle
                  style={{ width: 13, height: 13, color: "#94A3B8" }}
                />
                <p style={{ fontSize: 11, color: "#94A3B8", fontWeight: 600 }}>
                  This is a simulated payment. No real transaction will occur.
                </p>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
